<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>select_the_from_city_option</description>
   <name>select_the_from_city_option</name>
   <tag></tag>
   <elementGuidId>252cb29a-73b3-42d7-b2ad-e7efae823092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id=&quot;react-autowhatever-1-section-0-item-0&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
